services:
  convertx:
    build:
      context: .
      # dockerfile: Debian.Dockerfile
    volumes:
      - .:/app # Mounts the project directory
      - /app/node_modules # Prevents overwriting node_modules
      - ./data:/app/data
    environment: # Defaults are listed below. All are optional.
      - HTTP_ALLOWED=true # setting this to true is unsafe, only set this to true locally
      - AUTO_DELETE_EVERY_N_HOURS=1 # checks every n hours for files older then n hours and deletes them, set to 0 to disable
      # - FFMPEG_ARGS=-hwaccel vulkan # additional arguments to pass to ffmpeg
      # - WEBROOT=/convertx # the root path of the web interface, leave empty to disable
    ports:
      - 3000:3000
